### ISSUE TITLE
MinimumScaleMode.Fit and coordinates

### ISSUE THREAD

**Issue by krabo0om** [moagrius/TileView#338] opened 2016-08-21 11:49 UTC
Hey,
thanks to @tsuijten and @peterLaurence  PR #318 introduced the `MinimumScaleMode.Fit` mode adding whitespaces when totally zoomed out.
However, this broke the coordinates of tap events. A short example:
_Lets say I have an image of 1000 width * 500 height and set `MinimumScaleMode.FIT`. Zoomed totally in at 1.0 and tapping the lower right I get x,y of 1000,500. Fine.
Zooming out it adds the whitespaces and centres the image, also fine. However, if I tap the lower right now I get x,y of something like 1000,2500 because the added whitespace._
This offset is calculated in `ZoomPanLayout.onLayout()` with `translateX` and `translateY` and should be used to offset the `MotionEvent` the `onTouchEvent()` gets.

**Comment by peterLaurence** [comment] 2016-08-21 16:20
I can confirm this. I tested the changes suggested and it fixes the issue, although i'm not yet sure this is the correct way to fix this nor this won't have side effects. Nevertheless, the changes can be seen on my fork, [banch `fix#338`](https://github.com/peterLaurence/TileView/tree/fix%23338).
It can now be checked with the `RealMapTileView` demo.

@moagrius you can check the changes, and if you agree i can PR. FYI, i logged the values of `translateX` and `translateY` during layout change. They were equal to 0 except when i zoomed out enough to see white spaces.

**Comment by moagrius** [comment] 2016-08-21 22:26
i commented your fork peter

**Comment by moagrius** [comment] 2016-08-23 01:15
@krabo0om  this should be fixed in https://github.com/moagrius/TileView/commit/ad43318f2301822b4bfae4adea67ec5695df72b8 - can you grab the latest master and confirm?  if it works, i'll publish a release

@peterLaurence i skipped a PR (no real reason just rushing i guess) - does this look sane to you?

**Comment by peterLaurence** [comment] 2016-08-23 09:09
@moagrius it looks ok for me. It fixes the markers part. One last thing is the HotSpots (aka `Region`s) are not offset, so it looks to me that the modified touch event position can lead to wrong HotSpot match.

**Comment by krabo0om** [comment] 2016-08-23 10:58
@moagrius  looks good to me, too.
My callout view is not chopped any more and my hot spots are all working.

**Comment by peterLaurence** [comment] 2016-08-23 11:01
@krabo0om your HotSpots are working even when you ave white spaces (in FIT mode)?

**Comment by krabo0om** [comment] 2016-08-23 11:15
@peterLaurence yeah they do :smile:

**Comment by peterLaurence** [comment] 2016-08-23 11:16
Ok i must be missing something. Good news anyway.

**Comment by krabo0om** [comment] 2016-08-23 12:20
there might be a new bug with callouts and `clipChildren=true`:
[![disappearing callout](https://s14.postimg.org/irt0pr5s1/ezgif_com_resize.gif)](https://postimg.org/image/if1mjkni5/)
So when I show the callout I pull data from a server, the progress bar shows that. After that's done I set the visibility of the progress bar to `View.GONE` resulting in a new layout phase. The view itself stays visible and it's position isn't changed, however, it disappears (after the progress bar is gone) when it's not inside the `MarkerLayout` any longer.
I guess that the systems hides the view because it left the parent.

**Comment by peterLaurence** [comment] 2016-08-23 12:29
Try to set the visibility of the marker to `View.VISIBLE` right after you set `View.GONE` on the progressbar?

**Comment by krabo0om** [comment] 2016-08-23 12:43
the view's visibility is not affected it's always `View.VISIBLE`, I used a `View.OnLayoutChangeListener` (fired when the progress bar is gone) and a `OnAttachStateChangeListener` (fired when the callout is removed because of a tap on the image) to confirm this. The disappearing view behaves the same as a view inside the `MarkerLayout`

**Comment by krabo0om** [comment] 2016-08-23 12:47
I could not get the `CalloutLayout`'s `moveMarker` working to move it back inside the `MarkerLayout` to confirm that the system just ignores the callout during the render phase.

**Comment by peterLaurence** [comment] 2016-08-23 13:21
I can't reproduce on my side. Callouts stay visible even when outside and when a child view's visibility is set to `View.GONE`.

**Comment by peterLaurence** [comment] 2016-08-23 13:33
So as a workaround, you can adjust the `anchorY` value for that disappearing callout, so it gets at least partially inside the visible tiles.

**Comment by krabo0om** [comment] 2016-08-23 13:37
this works for now (I used `View.offsetTopAndBottom`).
I'll try to reproduce it with the demo app.

**Comment by peterLaurence** [comment] 2016-08-23 13:44
I found the fix. `setClipChildren( false );` has to be added in `MarkerLayout` constructor too.
In that particular case, the `MarkerLayout` was clipping its child view.

**Comment by krabo0om** [comment] 2016-08-23 13:57
I can confirm it's working with `setClipChildren( false )` in the `MarkerLayout`

**Comment by krabo0om** [comment] 2016-08-23 15:06
okay I hope this is the last thing: Callouts won't be closed when tapping in the whitespace.
This should solve it (in `TileView`):
```
  @Override
  public boolean onTouchEvent(MotionEvent event) {
    mMarkerLayout.onTouchEvent( event );
    mCalloutLayout.onTouchEvent( event );
    return super.onTouchEvent( event );
  }
```

**Comment by moagrius** [comment] 2016-08-23 21:51
the time difference is a killer!

anyways, IIUC i need to add 2 things:

1.  setClipChildren in MarkerLayout
2.  pass touch event to the CalloutLayout

i'll post those, let me know if i missed anything, otherwise i'll generate a release tomorrow

thanks guys

**Comment by moagrius** [comment] 2016-08-23 21:55
ok it's up

**Comment by peterLaurence** [comment] 2016-08-23 22:12
Looks good to me. Though i noticed that a touch inside a `SampleCallout` causes it to disappear, while it seems to me that it didn't before. I don't know if it's a problem anyway.

**Comment by moagrius** [comment] 2016-08-23 22:16
it will unless the callout view consumes the event (e.g., with a click listener)

thanks peter, i'll bump versions and generate a release

i appreciate all your help, as always

**Comment by moagrius** [comment] 2016-08-23 22:38
2.2.1 is out

**Closed by moagrius** 2016-08-23 22:38 UTC
