### ISSUE TITLE
last tile is stretching

### ISSUE THREAD

**Issue by RemyDupont** [moagrius/TileView#356] opened 2016-10-20 14:03 UTC
hi, 

Here is my problem, as you can see below, the last tile, which is not a square is stretching.
Same thing with zoomed tiles

Right right one
![0_0](https://cloud.githubusercontent.com/assets/22959691/19563169/602e3128-96df-11e6-9097-fa6dade2cde9.jpg)

The tiled image
![screenshot_2016-10-20-16-04-32](https://cloud.githubusercontent.com/assets/22959691/19563194/7346d44a-96df-11e6-982b-c497f92ced19.png)

Do you have any idea to solve it ?

Thanks

**Comment by moagrius** [comment] 2016-10-20 18:18
closing this, duplicate of #357

**Closed by moagrius** 2016-10-20 18:18 UTC

**Comment by moagrius** [comment] 2016-10-20 18:20
yeah this is a bug, i know what's causing it.  i'll get a fix out when i can, probably this weekend.  if you need a temporary workaround, you can either fork the repo and i'll tell you what to change, or you can make your edge tiles full size with transparent pixels.  if you can wait a few days, that's probably best.

thanks for catching it.
