### ISSUE TITLE
Sorry,Here i go again!

### ISSUE THREAD

**Issue by parcool** [moagrius/TileView#335] opened 2016-08-19 10:59 UTC
When mapview(image) less than screen,in other words,when there is interspace between mapview and screen edge ,click the marker and the `callout` show incorrect position.

do you think this is a way to fix it?
in `MarkerLayout.java`,
add `y -= getTop();
        x -= getLeft();` after line 89.

**Comment by moagrius** [comment] 2016-08-19 20:06
that change would break the code in that method in a number of ways - both `getTop` and `getLeft` will always refer to the `MarkerLayout` instance, not the TileView, or the marker Views, and will always return 0.  If it did not return 0, I'm not sure how that would help - especially since line 89 is in a loop so both X and Y would be decremented by top and left times the number of children.  This is definitely not a fix.

I'm really not clear on the issue you're describing.  Can you please provide STR (steps to reproduce) in one of the demos, and any other information you think would be helpful.

Thanks.

**Comment by parcool** [comment] 2016-08-20 06:29
here is the [video](http://yibogame.com/XXX.mp4) to shows what the situation,we can see the touch point which by my pinch zoom and tap,when i [add this two lines](http://yibogame.com/code.png) here,and the problem occur never(yes!i add this `tileView.setMinimumScaleMode(ZoomPanLayout.MinimumScaleMode.FIT);` code).

**Comment by peterLaurence** [comment] 2016-08-21 16:21
Confirmed. Duplicate of #338.

**Comment by moagrius** [comment] 2016-08-21 22:25
@parcool thanks for you patience and possible fix - this issue has been accepted and is being worked on.  

you referenced line 89 earlier, which in master is in the loop, so my comments in https://github.com/moagrius/TileView/issues/335#issuecomment-241121280 might not have made sense

**Comment by moagrius** [comment] 2016-08-23 01:14
@parcool this should be fixed in https://github.com/moagrius/TileView/commit/ad43318f2301822b4bfae4adea67ec5695df72b8 - can you grab the latest master and confirm?  if it works, i'll publish a release

**Comment by moagrius** [comment] 2016-08-23 01:16
you'll need to grab the latest `master` and run from code, not release

thanks

**Comment by moagrius** [comment] 2016-08-23 22:38
2.2.1 should fix your issue, re-open or post back if you're still having trouble

thanks for the report

**Closed by moagrius** 2016-08-23 22:38 UTC
