### ISSUE TITLE
Tileview not centring

### ISSUE THREAD

**Issue by iCRG** [moagrius/TileView#314] opened 2016-05-31 14:19 UTC
Hi all,
           Is there anyways, I can set the tileView to centre bcz i wanted to show full tileView where tileView width must be smaller than the available screen width. Currently tileView is starting from top Left corner and taking full screen even though tileView width is smaller then screen width.

**Comment by peterLaurence** [comment] 2016-05-31 15:33
Duplicate of #245?

**Comment by moagrius** [comment] 2016-06-01 00:01
looks like it.  i should probably publish a wiki at some point to do it with modifying the core, in another layout...

**Comment by iCRG** [comment] 2016-06-01 07:15
But even though tileView shows smaller than available space, it listens for tap even outside the tileView which u can think as a whitespace. There is any way to atleast stop tap listening which happened outside the tileView.

**Comment by tsuijten** [comment] 2016-06-13 18:25
I also need the image to center when setShouldScaleToFit = false. Additionally I don't want the image getting smaller then the canvas, which is currently possible. 

I'll try to fix what I want and create a PR.

**Comment by moagrius** [comment] 2016-07-25 01:20
this should be resolved in 2.1.8 - reopen if your issue is not resolved

**Closed by moagrius** 2016-07-25 01:20 UTC

**Comment by moagrius** [comment] 2016-07-25 01:25
ref https://github.com/moagrius/TileView#scaling
