### ISSUE TITLE
"This class was probably produced by a compiler that did not target the modern .class file format"

### ISSUE THREAD

**Issue by Dev-iL** [moagrius/TileView#285] opened 2016-04-03 22:40 UTC
Hi guys,
Does anybody know anything about this problem? I'm getting this during compilation. The app runs fine, but this is somewhat disturbing as it appears as an error and adds to the error count... :\

```
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.qozix.tileview.TileView$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.

Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.qozix.tileview.TileView$SavedState$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.

Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.qozix.tileview.tiles.TileCanvasViewGroup$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
```
I'm testing this on:

- API 23 device (ASUS Zenfone 2 Z00A).
- Android Studio 2.1 preview 5.
- `'com.android.tools.build:gradle:2.1.0-alpha5'`
- `'com.google.gms:google-services:2.1.0-alpha4'`
- `'com.qozix:tileview:2.1.2'`
- Gradle 2.12
- And also:
```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_7
}
```

**Comment by moagrius** [comment] 2016-04-05 18:29
I have not seen that before - please post back if you get any further information.

**Comment by Dev-iL** [comment] 2016-04-05 20:05
@moagrius Is there anything you would like me to check? I could try compiling the library from source using the latest gradles and see if these warnings go away....

**Comment by moagrius** [comment] 2016-04-07 00:12
i think that might be a proguard thing...?  i'm really not sure though, i'll leave this open until i get some time to poke around

**Comment by peterLaurence** [comment] 2016-04-07 12:38
Is it intended to use an alpha version of build.gradle?

**Comment by Dev-iL** [comment] 2016-04-07 15:16
@peterLaurence - Looks like I am... It could mean several things though: either they screwed up something in Gradle, "I'm using it wrong", or some change (minor as it may be) will need to be included in the library. I suppose time will tell which it is.. Right now we should likely wait for more people to transition to Android Studio 2.0 (and higher), and see if they run into similar errors. 

As I originally mentioned, these "errors" don't stop the code from compiling and running - so it might not be that urgent to resolve....

**Comment by peterLaurence** [comment] 2016-04-07 20:55
@Dev-iL I agree

**Comment by peterLaurence** [comment] 2016-04-08 23:11
I upgraded to Android Studio 2.0 tonight, and i can confirm the errors posted in OP with using :

- API 23 (Nexus 5)

- build tools 23.0.3

- gradle 2.10

- plugin 2.0.0

After compiling TileView from source with updated build tools, gradle, etc the errors are still showing. **But** after disabling proguard (by setting `minifyEnabled false`) in TileView, i get no error.

So although the errors don't prevent the app from working fine, it seems to be between proguard and the new chain of compilation.

**Comment by AndrazP** [comment] 2016-04-15 11:01
#294 
Hi guys,
Adding "-keepattributes EnclosingMethod" to proguard rules suppresses this warnings.

**Comment by peterLaurence** [comment] 2016-04-15 11:59
Nice! Thank you.

**Comment by moagrius** [comment] 2016-04-29 23:04
can we close this?

**Comment by Dev-iL** [comment] 2016-04-29 23:06
@moagrius is there a released version where the fix for the issue is included?

**Comment by moagrius** [comment] 2016-04-29 23:07
should be in 2.1.5

**Comment by Dev-iL** [comment] 2016-04-29 23:12
Then - by all means! :)

**Comment by moagrius** [comment] 2016-04-29 23:20
i'm not seeing any similar warnings on an app using 2.1.5, so closing it.

thanks @Dev-iL for posting!

**Closed by moagrius** 2016-04-29 23:20 UTC
