### ISSUE TITLE
Marker and Hotspot Touches Not Accurate

### ISSUE THREAD

**Issue by MisterRager** [moagrius/TileView#347] opened 2016-10-03 17:46 UTC
I've got some markers on my `TileView` that I'm listening to like this:

```
        sheetView.setMarkerTapListener((view, x, y) -> {
            Logger.getInstance().info(TAG, "Clicked view at [%d, %d]", x, y);
        });

```

This is firing events on touches that seem to be based on a different scaling level than what I can see: empty areas fire off events for markers nowhere near the actual touch, and the actual touched areas do not result in the touches expected. Additionally, I can't seem to actually "touch" any of the hotspots I added.

Thanks!

**Comment by MisterRager** [comment] 2016-10-03 19:34
After investigating some more, it appears that the touches are not even lining up with marker views that are offset from or scaled from the touch's position.

**Comment by MisterRager** [comment] 2016-10-03 19:39
The `mHitRect` value in the view's layout params seems to have little to no bearing on the actual view's location:

Click is at `(596, -62)`, view actually selected is closer to `(590, 40)`,  hit rect is supposedly `Rect(97, -221  -  1177, 550)`.

**Comment by moagrius** [comment] 2016-10-03 22:06
what version are you using?

if it's the latest, can you fork the repo and modify one of the demos to display the issue you're seeing?

remember that both layout and "normal" hit rect in android do not scale normally, which is why we have to manage it.

**Comment by moagrius** [comment] 2016-10-07 00:15
following up - is this still an open issue for you @MisterRager

**Comment by MisterRager** [comment] 2016-10-07 19:59
Yes, but I haven't had time to investigate further since I have abandoned using the marker views to replace some extant views for now. Sorry for that. I'll try to look at it once I have a bit more bandwidth.

**Comment by moagrius** [comment] 2016-10-08 23:31
np - if you have time and could just post the version, that may make the rest moot

**Comment by MisterRager** [comment] 2016-10-10 23:33
2.2.2

**Comment by moagrius** [comment] 2016-10-10 23:58
thanks, it's not a version issue, i'll take a look

**Comment by moagrius** [comment] 2016-10-16 19:04
i just tested and both HotSpots and Markers are working as intended.  Are you saying that HotSpots you registered were not invoking attached HotSpotListeners.onHotSpotTap method?  Or are you just saying that the x and y values reported to that method are not what you expected?

To see HotSpots working, you can dd this block to RealMapTileViewActivity:

```
tileView.addHotSpot( points.subList( 1, 5 ), new HotSpot.HotSpotTapListener() {
  @Override
  public void onHotSpotTap( HotSpot hotSpot, int x, int y ) {
    Log.d("TileView", "HotSpot tapped");
  }
} );
```

If you tap near Second Bank of the United States, Carpenters Hall, Benjamin Franklin Museum or Franklin Court, you'll see the log.  This happens at any scale.

Note that the coordinates reported are not scaled, and are offset - IIRC that number represents the "real" pixel value (as if there were no scaling, from top left - basically the x of the screen plus the scroll position).  You can translate that to coordinates or scale it, if that better suits your needs.  Here's the relevant line where that x and y are determined: 

https://github.com/moagrius/TileView/blob/master/tileview/src/main/java/com/qozix/tileview/TileView.java#L858.  

You can also see that the HitRect used by MarkerLayout.LayoutParams is exactly what is used for layout - in fact they reference the identical properties:

https://github.com/moagrius/TileView/blob/master/tileview/src/main/java/com/qozix/tileview/markers/MarkerLayout.java#L146
https://github.com/moagrius/TileView/blob/master/tileview/src/main/java/com/qozix/tileview/markers/MarkerLayout.java#L206

This may seem less than obvious since the markers _move_ as the TileView scales, but do not scale themselves.

If the above doesn't address your issue, please provide detailed STR and a branch or fork of one of the included demo activities with just enough modifications to demonstrate the problem.

**Comment by moagrius** [comment] 2016-10-20 18:21
closing for now, but i'll be alerted when/if you follow up and we can re-open if necessary

**Closed by moagrius** 2016-10-20 18:21 UTC
